import Head from 'next/head'
import Header from '../components/Header';
import Nav from '../components/Nav';
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Hulu clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header/>
      <Nav/>
    </div>
  )
}
